// Zasady gramatyczne HSK (zbiór reguł, krótko)
(function(){
    const rules = [
        "L1P1: 好 as a successful completion of an action | 准备好了吗？ | Are you ready?",
        "L1P2: ”not at all” (不 for present/future, 没 for past) | 我今天没吃早饭。 | I didn't eat breakfast today.",
        "L1P3: 那 → continuation of the previous statement | 那，我们走吧。 | Well then, let's go.",
        "L2P1: V+来|去 → from | to in my direction | 老师走进来。 | The teacher walked in.",
        "L2P2: V1了。。。就V2 → when V1 finished, V2 happened immediately | 我吃了饭就去睡觉。 | I'll go to bed as soon as I finish eating.",
        "L2P3: 能。。。吗？→ rhetorical question | 这么小的孩子能听懂吗？ | Can such a small child understand (rhetorical)?",
        "L3P1.1: 还是 = or (in questions) | 你想喝茶还是咖啡？ | Do you want to drink tea or coffee?",
        "L3P1.2: 还是 = still / nevertheless (decision unchanged) | 他还是没来。 | He still didn't come.",
        "L3P1.3: 或者 → or / either...or (in affirmative sentences) | 你可以坐公共汽车或者打车。 | You can take a bus or a taxi.",
        "L3P2: 正在/着/在 used to indicate something is located somewhere | 墙上挂着一幅画。 | There is a painting hanging on the wall.",
        "L3P3: 会 as possibility | 天气预报说今天会下雨。 | The weather forecast says it might rain today.",
        "L4P1: 又...又... → both...and... | 她又聪明又漂亮。 | She is both smart and beautiful.",
        "L4P2: V1着O1 + V2O2 → coś się dzieje w tym samym momencie; takie while",
        "L5P1: 我现在没钱了 → 了 jako zmiana (np. kiedyś nie miałem, teraz mam)",
        "L5P2: 越来越冷 → coraz bardziej (np. coraz i coraz zimniej)",
        "L6P1: V很|不 → mogę/nie mogę coś zrobić",
        "L6P2: N+ 听 → where is sth? / słyszałeś (wiesz) gdzie to jest?",
        "L6P3: 刚 | 刚才 → coś się stało przed chwilą (刚才 dla minut, 刚 dla dni/tyg/mies)",
        "L7P1: 看了一个小时书了 → dodanie 了 do czasu oznacza, że coś było i nadal trwa",
        "L7P2: 高兴去 → interesuje się tym, dodawane na końcu zdania",
        "L8P1: 又 + verb → The recurrence has already happened | 我昨天看了一个电影，今天又看了一个。 | I watched a movie yesterday, and I watched another one today.",
        "L8P1: 再 + verb → The recurrence has not happened yet | 你只吃了一点儿饭，再吃一点儿吧。 | You only ate a little food. Have some more, please.",
        "L8P2: clause 1 + 就 + clause 2 → When the two clauses of a sentence share one subject, the subject of the second clause can be left out. | 你哪天有时间就哪天来我家吧。 | Come over to my place whenever you're free.",
        "L8P2: clause 1 + 就 + clause 2 → when the two clauses have different subjects, the second subject is put right before 就. | 你哪天有时间就哪天来我家吧。 | Come over to my place whenever you're free.",
        "L9P1: 越 A 越 B → the more A, the more A | 山越高，路越难走。 | The higher the mountain is, the harder the road to climb.",
        "L9P2: A 跟 B 一样 → A is the same with B. | 这本书跟那本书一样。 | This book is the same as that one.",
        "L9P2: A 跟 B 不一样 → A is not the same with B. | 这本书跟那本书不一样。 | This book is not the same as that one.",
        "L9P2: A 跟 B 一样 + adjective → A is as + adjective + as B. | 儿子跟爸爸一样高。 | The son is as tall as his father.",
        "L9P2: A 跟 B 不一样 + adjective → A is not as + adjective + as B. | 儿子跟爸爸不一样高。 | The son is not as tall as his father.",
        "L10P1: A 比 B + adjective + 一点儿/一些/得多/多了 → A positive form indicating the degree of difference between things | 数学比历史难多了。 | Math is much harder than history.",
        "L10P1: A 没有 B (+ 这么/那么) + adjective → A negative form indicating the degree of difference between things | 数学没有历史（那么）难。 | Math isn’t as hard as history.",
        "L10P2: two adjacent numerals (+ measure word) + noun → Indicating an approximate number | 我每天学习一两个小时汉语。 | I learn Chinese for one or two hours daily.",
        "L11P1.1: A 把 B + V + …… → Indicating a certain action done on a definite person or thing, often used for declaration, order, request | 你把灯关了吧。 | Could you turn off the light?",
        "L11P1.2: A + 没/别/不能 + 把 B + V + …… → Negative form of ba-sentence | 你没把书给我。 | You didn’t give me the book.",
        "L11P1.3: A + 能/可以/需要 + 把 B + V + …… + 吧？/吗？ → Interrogative form of ba-sentence | 你可以把电视关了吗？ | Could you turn off the TV?",
        "L11P2: number + measure word / noun of time + 左右 → Indicating an approximate number, means about or around | 周一我一般十点左右起床。 | I usually get up at about ten on Mondays.",
        "L12P1.1: 就 + verb → Indicating that in the speaker's opinion, the action happened early, or went on fast or smoothly | 我早上五点就起床了。 | I got up at 5 a.m.",
        "L12P1.2: 才 + verb → Indicating that in the speaker's opinion, the action happened late, or went on slowly or unsatisfactorily | 我早上九点才起床。 | I didn’t get up until nine o’clock in the morning.",
        "L12P2: 把 + verb + 在 / 到 + location → Indicating a certain action is done on a definite person or thing and has changed the location of the person or thing | 老师把书放在桌子上了。 | The teacher has put the book on the desk.",
        "L12P2.1: 把 + verb + 给 + somebody → An action has changed the owner or user of a definite object | 我把鲜花送给了老师。 | I gave the flowers to the teacher.",
        "L13P1.1: verb + 出 / 过 + noun + 来 / 去 → Compound complements of direction describing the direction of an action | 老师拿出一本书来。 | The teacher took out a book.",
        "L13P1.2: verb + 出 / 过 + 来 / 去 + noun → Compound complements of direction describing the direction of an action | 老师拿出来一本书。 | The teacher took out a book.",
        "L13P1.3: verb + 出 / 过 + place + 来 / 去 → Describing the direction of an action | 老师走进教室来。 | The teacher walked into the classroom.",
        "L13P2: 一边……一边…… → ... while / as ... | 老师边说边笑。 | The teacher laughed as she talked.",
        "L14P1: A 把 B + verb + Complement of Result / Direction → An action brings a result or changes position | 我把衣服洗干净了。 | I have got the clothes washed clean.",
        "L15P1.1: 除了……(以外)，都…… → all... except... | 除了我(以外)，其他人都走了。 | All the others have gone except me.",
        "L15P1.2: 除了……(以外)，还 / 也…… → besides... | 除了汉语(以外)，我还会说英语。 | I can speak English besides Chinese.",
        "L15P2: 什么 + noun → Polite demonstrative pronoun meaning an indefinite thing | 你写的很好，没什么问题。 | You wrote it really well; there's nothing wrong with it.",
        "L16P1: 如果……(的话)，(subject) 就…… → if..., then... | 如果你太累了，就休息一会儿。 | Have a rest if you're too tired.",
        "L16P2: verb / adjective + 得 + verbal phrase → Complex complements of state | 孩子们玩儿得不想回家。 | The kids are having so much fun that they don’t want to go home.",
        "L16P3: AA 的 → Reduplication of monosyllabic adjectives indicating a deep degree | 你送的花红红的，我很喜欢。 | The flowers you gave me are bright red, and I really like them.",
        "L17P1: verb + verb → Reduplication indicating a short action or attempt | 这是本新书，你学习学习吧。 | This is a new book. Give it a read.",
        "L17P2: 谁 / 什么 / 怎么 / 哪儿 + 都 → All without exception (positive & negative) | 谁都喜欢小丽。 | All people like Xiaoli.",
        "L17P2.1: 谁 / 什么 / 怎么 / 哪儿 + 也 → All without exception (mainly negative) | 我今天哪儿也不去。 | I'm not going anywhere today.",
        "L18P1.1: 只要 + subject1……，subject2 + 就…… → If..., then... | 只要你想去，我就跟你去。 | As long as you want to go, I'll go with you.",
        "L18P1.2: subject1 + 只要……，subject2 + 就…… → If..., then... | 你只要想去，我就跟你去。 | As long as you want to go, I'll go with you.",
        "L18P2: 关于 + noun → About / regarding something | 关于这个工作，还有什么问题吗？ | Do you have any other questions about this job?",
        "L19P1.1: verb + 出来 → Emergence of something new | 这个字你能写出来吗？ | Can you write this Chinese character?",
        "L19P1.2: verb + 出来 → Recognition of something implicit | 你听出来了吗？这是谁的声音？ | Did you recognize whose voice this is?",
        "L19P1.3: verb + 下来 → Change from movement to stillness | 前边的车越开越慢，停下来了。 | The car ahead slowed down and stopped.",
        "L19P1.4: adjective + 下来 → Change from high degree to low degree | 天气冷下来了，你多穿点衣服。 | It's getting cold. Put on more clothes.",
        "L19P1.5: verb + 下来 → Recalling reaches a result | 我想起来了，他是我的小学同学。 | It just came back to me. He was my classmate in primary school.",
        "L19P1.6: 看 / 听 / 闻 + 起来 / 上去 → Estimation or evaluation | 这个主意听起来不错。 | This idea sounds good.",
        "L19P2: 使 / 叫 / 让 + noun / pronoun + verb / adjective → To cause ... | 考试让我很紧张。 | Exams make me really nervous.",
        "L20P1.1: subject + 被 / 叫 / 让 + object + verb (+ 了) → Passive voice | 那个蛋糕给我吃了。 | That cake was eaten by me.",
        "L20P1.2: subject + 还没 / 会 + 被 / 叫 / 让 + object + verb → Passive with modal verbs | 我还没被开除。 | I haven't been fired yet.",
        "L20P1.3: 只有……才…… → Only if..., then... | 只有写完作业，才能看电视。 | Only when you finish your homework can you watch TV.",
    ];

    function getRandomGrammarRules(count){
        const shuffled = [...rules].sort(() => 0.5 - Math.random());
        return shuffled.slice(0, count);
    }

    window.GRAMMAR_RULES = {
        rules,
        getRandomGrammarRules
    };
})();
